config/routes.rb
Rails.application.routes.draw do
  root to: 'cheeps#home'

  resources :cheeps do
    collection do
      post :confirm
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites, only: [:create, :destroy, :index]
  resources :contacts, only: [:new, :create,:index, :destroy] do
    collection do
      post :confirm
    end
  end


  mount LetterOpenerWeb::Engine, at: "/letter_opener"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cheep.rb
class Cheep < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  validates :content,
  presence: true,
  length: { in: 1..140, allow_blank: true }

  mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, allow_blank: true }
  validates :content, presence: true, length: { maximum: 1000 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :cheep
end

app/models/user.rb
class User < ApplicationRecord

  has_many :cheeps, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_cheeps, through: :favorites, source: :cheep

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6, allow_blank: true }, on: :create

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/cheeps_controller.rb
class CheepsController < ApplicationController
  before_action :set_cheep, only: [:edit, :update, :destroy, :show]
  before_action :set_cheep_params, only: [:confirm, :create]
  before_action :user_logged_in?, only: [:new, :edit, :show, :destroy]

  def home
  end

  def index
    @cheeps = Cheep.includes(:user).reverse_order
  end

  def new
    if params[:back]
      set_cheep_params
    else
      @cheep = Cheep.new
    end
  end

  def confirm
    render :new if @cheep.invalid?
  end

  def edit
    if @cheep.user_id != current_user.id
      redirect_to cheeps_path
    end
  end

  def show
    @favorite = current_user.favorites.find_by(cheep_id: @cheep.id)
  end

  def create
    if @cheep.save
      CheepMailer.cheep_mail(@cheep).deliver
      redirect_to cheeps_path, notice: 'cheepしました！'
    else
      render :new
    end
  end

  def update
    if @cheep.update(cheep_params) && @cheep.user_id == current_user.id
      redirect_to cheeps_path, notice: '編集しました！'
    else
      render :edit
    end
  end

  def destroy
    if @cheep.user_id == current_user.id
      @cheep.destroy
      redirect_to cheeps_path, notice: '削除しました。'
    end
  end

  private

  def set_cheep
    @cheep = Cheep.find(params[:id])
  end

  def cheep_params
    params.require(:cheep).permit(:content, :image, :image_cache)
  end

  def set_cheep_params
    @cheep = current_user.cheeps.build(cheep_params)
  end

  def user_logged_in?
    unless logged_in?
      redirect_to new_session_path
    end
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact_params, only: [:confirm, :create]

  def index
    @contacts = Contact.all.reverse_order
  end

  def new
    @contact = Contact.new
  end

  def confirm
    render :new if @contact.invalid?
  end

  def create
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to contacts_path, notice: '送信しました！'
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end

  def set_contact_params
    @contact = Contact.new(contact_params)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(cheep_id: params[:cheep_id])
    redirect_to cheeps_url, notice: "#{favorite.cheep.user.name}さんのCheepをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to cheeps_url, notice: "#{favorite.cheep.user.name}さんのCheepをお気に入り解除しました"
  end

  def index
    @cheeps = current_user.favorite_cheeps.reverse_order
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to cheeps_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path, notice: '編集しました！'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation,
                                 :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cheeps_helper.rb
module CheepsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_cheeps_path
    elsif action_name == 'edit'
      cheep_path
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cheeps/_form.html.erb
<%= form_with(model: @cheep, local: true, url: choose_new_or_edit) do |form| %>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 box">
      <% if @cheep.errors.any? %>
        <div id="error_explanation">
          <h2><%= @cheep.errors.count %>件のエラー</h2>

          <ul>
            <% @cheep.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 box">
      <div class="field">
        <%= form.text_area :content, id: :cheep_content %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 box">
      <div class="field">
        <%= image_tag (@cheep.image.url) if @cheep.image.url %>
        <%= form.file_field :image, id: :cheep_image %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 box">
      <div class="actions">
        <%= form.submit '送信', class: 'btn btn-default' %>
      </div>
    </div>
  </div>
<% end %>

app/views/cheeps/confirm.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 box">
      <h2>以下の内容で送信します</h2>

      <%= form_with(model: @cheep, url: cheeps_path, local: true) do |form| %>
        <%= form.hidden_field :content %>
        <%= form.hidden_field :image_cache %>

        <div class="confirm_text">
          <p>内容</p>
          <p><%= @cheep.content %></p>
          <%= image_tag @cheep.image %>
          <%= form.submit "送信する", class: 'btn btn-default' %>
        </div>
      <% end %>

      <%= form_with(model: @cheep, url: new_cheep_path, local:true, method: 'get') do |form| %>
        <%= form.hidden_field :content %>
        <%= form.hidden_field :image_cache %>
        <%= form.submit "戻る", name: 'back', class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cheeps/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 box">
      <h2>編集する</h2>
    </div>
  </div>

  <%= render 'form' %>

  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 box">
      <%= link_to '戻る', cheeps_path, class: 'btn btn-default' %>
    </div>
  </div>
</div>

app/views/cheeps/home.html.erb
<div class="jumbotron">
  <div class="container width-100">
      <p>ひよっこのひとりごと</p>
  </div>
</div>

app/views/cheeps/index.html.erb
<div class="container">
  <div class="container cheep_button_area">
    <%= link_to 'cheepする', new_cheep_path, class: 'btn btn-default' %>
  </div>
  <div class="container">
    <div class="row">
      <% @cheeps.each do |cheep| %>
        <div class="col-lg-3 col-md-4 col-sm-6">
          <div class="content_background">
            <div class="content_area">
              <div class="content_header">
                <span><%= cheep.user.name %></span>
                <% if cheep.user.image.present? %>
                  <%= image_tag cheep.user.image, class: 'user_image' %>
                <% else %>
                  <%= image_tag 'avatar.jpg', class: 'user_image' %>
                <% end %>
              </div>
              <div class="content_text">
                <p><%= cheep.content %></p>
              </div>
              <div class="content_image">
                <%= image_tag (cheep.image.thumb.url) if cheep.image.url %>
              </div>
              <div class="content_datetime">
                <p><%= cheep.created_at.time.strftime("%Y年%m月%d日 %H時%M分") %></p>
              </div>
              <div class="edit_button">
                <%= link_to '詳細', cheep %>
                <% if cheep.user_id == current_user.id %>
                  <%= link_to '編集', edit_cheep_path(cheep) %>
                  <%= link_to '削除', cheep, method: :delete, data: { confirm: '削除してもよろしいですか？' } %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cheeps/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 box">
      <h2>Cheepする</h2>
    </div>
  </div>

  <%= render 'form' %>

  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 box">
      <%= link_to 'Back', cheeps_path, class: 'btn btn-default' %>
    </div>
  </div>
</div>

app/views/cheeps/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <p>
        <strong>Content:</strong>
        <%= @cheep.content %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <p>
        <strong>Image:</strong>
      </p>
      <%= image_tag @cheep.image %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 box">
      <% if @cheep.user_id == current_user.id %>
        <%= link_to 'Edit', edit_cheep_path(@cheep), class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 box">
      <%= link_to 'Back', cheeps_path, class: 'btn btn-default' %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 box">
      <% unless @cheep.user == current_user %>
        <% if @favorite.present? %>
          <%=
            link_to 'お気に入り解除する',
            favorite_path(id: @favorite.id),
            method: :delete,
            class: 'btn btn-danger'
          %>
        <% else %>
          <%=
            link_to 'お気に入りに登録',
            favorites_path(cheep_id: @cheep.id),
            method: :post,
            class: 'btn btn-primary'
          %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">

      <%= form_with(model: contact, class: 'form-contact', local: true, url: confirm_contacts_path) do |form| %>

        <% if @contact.errors.any? %>
          <div id="error_explanation">
            <h2><%= @contact.errors.count %> 件のエラー</h2>

            <ul>
              <% @contact.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field contact-field-name">
          <%= form.label '名前' %>
          <%= form.text_field :name, tabindex: '1', autofocus: 'autofocus' %>
        </div>

        <div class="field contact-field-email">
          <%= form.label 'メールアドレス' %>
          <%= form.text_field :email, tabindex: '2' %>
        </div>

        <div class="field contact-field-content">
          <%= form.label 'お問い合わせ内容' %>
          <%= form.text_area :content, tabindex: '3' %>
        </div>

        <div class="field">
          <%= form.submit '送信', class: 'btn btn-default', tabindex: '4' %>
        </div>

        <div class="back-link">
          <%= link_to '戻る', contacts_path, tabindex: '5' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/confirm.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 box">
      <h2>以下の内容で送信します</h2>

      <%= form_with(model: @contact, url: contacts_path, local: true) do |form| %>
        <%= form.hidden_field :name %>
        <%= form.hidden_field :email %>
        <%= form.hidden_field :content %>

        <div class="confirm_text">
          <p>内容</p>
          <p><%= @contact.content %></p>
          <%= form.submit "送信する", class: 'btn btn-default' %>
        </div>
      <% end %>

      <%= form_with(model: @contact, url: new_contact_path, local: true) do |form| %>
        <%= form.hidden_field :content %>
        <%= form.submit "戻る", name: 'back', class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="container">
  
  <h1>Contacts</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.name %></td>
          <td><%= contact.email %></td>
          <td><%= contact.content %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-3 box">
      <h2>お問い合わせ</h2>
    </div>
  </div>
</div>

<%= render 'form', contact: @contact %>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/index.html.erb
<div class="container">
  <div class="container cheep_button_area">
    <%= link_to 'cheepする', new_cheep_path, class: 'btn btn-default' %>
  </div>
  <div class="container">
    <div class="row">
      <h2>お気に入り一覧</h2>
      <% @cheeps.each do |cheep| %>
        <div class="col-lg-3 col-md-4 col-sm-6">
          <div class="content_area">
            <div class="content_text">
              <p><%= cheep.content %></p>
            </div>
            <div class="content_datetime">
              <p><%= cheep.created_at.time.strftime("%Y年%m月%d日 %H時%M分") %></p>
            </div>
            <div class="edit_button">
              <%= link_to '詳細', cheep %>
              <% if cheep.user_id == current_user.id %>
                <%= link_to '編集', edit_cheep_path(cheep) %>
                <%= link_to '削除', cheep, method: :delete, data: { confirm: '削除してもよろしいですか？' } %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="container">
    <%= link_to 'Back', cheeps_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cheeper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <% if logged_in? %>
              <% home = cheeps_path %>
            <% else %>
              <% home = root_path %>
            <% end %>
            <%= link_to home, class: 'navbar-brand' do %>
              <%= image_tag('Cheeper_logo.png', class: 'logo make-this-white', alt: 'Bland') %>
            <% end %>

            <button type="button" class="navbar-toggle cllapsed" data-toggle="collapse" data-target="#global-navi">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>

          <div id="global-navi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Home", home %></li>
              <li><a href="">Features</a></li>
              <li><a href="">Samples</a></li>
              <li><%= link_to "Contact", new_contact_path %>
            </ul>
              <div class="collapse navbar-collapse navbar-right">
                <% if logged_in? %>
                  <span>User: <%= current_user.name %></span>
                  <%=
                    link_to "Favorites",
                    favorites_path,
                    class: 'btn btn-default navbar-btn'
                  %>
                  <%=
                    link_to "Profile",
                    user_path(current_user),
                    class: 'btn btn-default navbar-btn'
                  %>
                  <%=
                    link_to "Logout",
                    session_path(current_user),
                    method: :delete, class: 'btn btn-default navbar-btn'
                  %>
                <% else %>
                  <%= link_to "新規登録", new_user_path, class: 'btn btn-default navbar-btn' %>
                  <%= link_to "Log in", new_session_path, class: 'btn btn-default navbar-btn' %>
                <% end %>
              </div>
            </div>
          </div>
      </nav>
    </header>

    <div class="container flash_area">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
    </div>

    <%= yield %>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">&copy;Y.ito</p>
      </div>
    </footer>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <h1>アカウント編集</h1>

      <%= form_with(model: @user, url: user_path, local: true) do |form| %>

        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@user.errors.count, "error") %>
              prohibited this @user from being saved:
            </h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :image %>
          <%= form.file_field :image, id: :user_image %>
        </div>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name %>
        </div>

        <div class="form-group">
          <%= form.label :email %>
          <%= form.email_field :email %>
        </div>

        <%= form.submit "アカウント情報更新", class: 'users-submit' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <h1>アカウント新規作成</h1>

      <%= form_with(model: @user, local: true) do |form| %>

        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@user.errors.count, "error") %>
              prohibited this @user from being saved:
            </h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name, { class: 'hoge' }%>
          <%= form.text_field :name %>
        </div>

        <div class="form-group">
          <%= form.label :email %>
          <%= form.email_field :email %>
        </div>

        <div class="form-group">
          <%= form.label :password %>
          <%= form.password_field :password %>
        </div>

        <div class="form-group">
          <%= form.label :password_confirmation %>
          <%= form.password_field :password_confirmation %>
        </div>

        <%= form.submit "アカウント作成", class: 'users-submit' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row form-group">
    <h1><%= @user.name %>のページ</h1>
    <%= image_tag(@user.image.url) if @user.image.url %>
    <p>ユーザー名: <%= @user.name %></p>
    <p>メールアドレス: <%= @user.email %></p>
  </div>
  <div class="row">
    <%= link_to '編集', edit_user_path(@user), class: 'btn btn-default' %>
  </div>
</div>